pipeline:
  name: Build CucumberRediffMoneyTest
  identifier: Build_pushkarbhadang12_CucumberRediffMoneyTest_1704101445062
  projectIdentifier: seleniumcucumbertest
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1703314950386
        repoName: pushkarbhadang12/CucumberRediffMoneyTest
        build: <+input>
